#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")/.."
transport_temp="$(mktemp -d /private/tmp/GaoMailTransportTests.XXXXXX)"
server_pid=""
cleanup() {
  if [ -n "$server_pid" ]; then kill "$server_pid" 2>/dev/null || true; wait "$server_pid" 2>/dev/null || true; fi
  rm -rf "$transport_temp"
}
trap cleanup EXIT
cat > "$transport_temp/cert.cnf" <<'CERT'
[req]
distinguished_name=dn
x509_extensions=v3
prompt=no
[dn]
CN=localhost
[v3]
subjectAltName=DNS:localhost,IP:127.0.0.1
basicConstraints=critical,CA:TRUE
keyUsage=critical,digitalSignature,keyEncipherment,keyCertSign
CERT
/usr/bin/openssl req -x509 -newkey rsa:2048 -nodes -keyout "$transport_temp/key.pem" -out "$transport_temp/cert.pem" -days 1 -config "$transport_temp/cert.cnf" > "$transport_temp/openssl.log" 2>&1
python3 Tests/local_mail_server.py "$transport_temp" > "$transport_temp/server.log" 2>&1 &
server_pid=$!
for i in {1..100}; do [ -f "$transport_temp/ports.json" ] && break; sleep 0.05; done
ports="$(python3 -c 'import json,sys; print(*json.load(open(sys.argv[1])))' "$transport_temp/ports.json")"
clang -c Sources/MailNative.c -o "$transport_temp/MailNative.o"
swiftc -import-objc-header Sources/MailNative.h "$transport_temp/MailNative.o" -lcurl -swift-version 5 -module-cache-path "$transport_temp/modules" Sources/MailTransport.swift Tests/TransportTests.swift -o "$transport_temp/tests"
# Intentional word split: ports contains exactly four integers generated by our local fixture.
"$transport_temp/tests" "$transport_temp/cert.pem" $ports
python3 - "$transport_temp/state.json" <<'PY'
import json, sys
state = json.load(open(sys.argv[1]))
assert len(state['messages']) == 4, 'Unexpected DATA indicates partial send or automatic retry'
assert '<secret@example.invalid>' in state['recipients'], 'Bcc recipient missing from SMTP envelope'
assert 'secret@example.invalid' not in state['message'], 'Bcc leaked in delivered message'
assert state['messages'][0] == state['append'], 'Sent copy differs from transmitted MIME'
assert any('UID MOVE' in cmd for cmd in state['commands']), 'Move command missing'
assert any('BODY.PEEK[]' in cmd for cmd in state['commands']), 'Body fetch unexpectedly marks read'
assert not any('UID STORE 999' in cmd or 'UID MOVE 999' in cmd or 'UID FETCH 999' in cmd for cmd in state['commands']), 'Stale UID operation reached server'
assert not any('test-pass' in cmd for cmd in state['commands']), 'Test log exposed a password'
print('PASS: SMTP envelope privacy, identical sent copy, safe IMAP commands')
PY
